"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['GroeneveldShapes.py']
DATA_FILES = ['high_score.txt']
OPTIONS = {'iconfile': '/Users/groeneveld/Documents/Coding/Python/GroeneveldShapes/shapes.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
